class Dish{
  String restaurant;
  String dishName;
  String day;
  String typeOfDish;

  Dish(this.restaurant, this.dishName, this.day, this.typeOfDish);

  //Grill
  List<Dish> dishList = [
    //CARNE
    Dish('Grill',
        'Frango assado com arroz de tomate',
        'Segunda feira',
        'Carne'),
    Dish('Grill',
        'Lombo de porco assado com maçã',
        'Terça feira',
        'Carne'),
    Dish('Grill',
        'Frango assado com arroz de tomate',
        'Quarta feira',
        'Carne'),
    Dish('Grill',
        'Frango assado com arroz de tomate',
        'Quinta feira',
        'Carne'),
    Dish('Grill',
        'Frango assado com arroz de tomate',
        'Sexta feira',
        'Carne'),

    //PEIXE
    Dish('Grill',
        'Bacalhau fresco à zé do pipo',
        'Segunda feira',
        'Peixe'),
    Dish('Grill',
        'Truta com bacon com batata cozida',
        'Terça feira',
        'Peixe'),
    Dish('Grill',
        'Truta com bacon com batata cozida',
        'Quarta feira',
        'Peixe'),
    Dish('Grill',
        'Truta com bacon com batata cozida',
        'Quinta feira',
        'Peixe'),
    Dish('Grill',
        'Truta com bacon com batata cozida',
        'Sexta feira',
        'Peixe'),

    //DIETA
    Dish('Grill',
        'Frango grelhado com esparguete',
        'Segunda feira',
        'Dieta'),
    Dish('Grill',
        'Frango grelhado com esparguete',
        'Terça feira',
        'Dieta'),
    Dish('Grill',
        'Frango grelhado com esparguete',
        'Quarta feira',
        'Dieta'),
    Dish('Grill',
        'Frango grelhado com esparguete',
        'Quinta feira',
        'Dieta'),
    Dish('Grill',
        'Frango grelhado com esparguete',
        'Sexta feira',
        'Dieta'),

    //VEGETARIANO
    Dish('Grill',
        'Muqueca de tofu',
        'Segunda feira',
        'Vegetariano'),
    Dish('Grill',
        'Muqueca de tofu',
        'Terça feira',
        'Vegetariano'),
    Dish('Grill',
        'Muqueca de tofu',
        'Quarta feira',
        'Vegetariano'),
    Dish('Grill',
        'Muqueca de tofu',
        'Quinta feira',
        'Vegetariano'),
    Dish('Grill',
        'Muqueca de tofu',
        'Sexta feira',
        'Vegetariano'),

    //Restaurante FEUP

    //CARNE
    Dish('Cafetaria - Restaurante FEUP',
        'Frango assado com arroz de tomate',
        'Segunda feira',
        'Carne'),
    Dish('Cafetaria - Restaurante FEUP',
        'Lombo de porco assado com maçã',
        'Terça feira',
        'Carne'),
    Dish('Cafetaria - Restaurante FEUP',
        'Frango assado com arroz de tomate',
        'Quarta feira',
        'Carne'),
    Dish('Cafetaria - Restaurante FEUP',
        'Frango assado com arroz de tomate',
        'Quinta feira',
        'Carne'),
    Dish('Cafetaria - Restaurante FEUP',
        'Frango assado com arroz de tomate',
        'Sexta feira',
        'Carne'),

    //PEIXE
    Dish('Cafetaria - Restaurante FEUP',
        'Bacalhau fresco à zé do pipo',
        'Segunda feira',
        'Peixe'),
    Dish('Cafetaria - Restaurante FEUP',
        'Truta com bacon com batata cozida',
        'Terça feira',
        'Peixe'),
    Dish('Cafetaria - Restaurante FEUP',
        'Truta com bacon com batata cozida',
        'Quarta feira',
        'Peixe'),
    Dish('Cafetaria - Restaurante FEUP',
        'Truta com bacon com batata cozida',
        'Quinta feira',
        'Peixe'),
    Dish('Cafetaria - Restaurante FEUP',
        'Truta com bacon com batata cozida',
        'Sexta feira',
        'Peixe'),

    //DIETA
    Dish('Cafetaria - Restaurante FEUP',
        'Frango grelhado com esparguete',
        'Segunda feira',
        'Dieta'),
    Dish('Cafetaria - Restaurante FEUP',
        'Frango grelhado com esparguete',
        'Terça feira',
        'Dieta'),
    Dish('Cafetaria - Restaurante FEUP',
        'Frango grelhado com esparguete',
        'Quarta feira',
        'Dieta'),
    Dish('Cafetaria - Restaurante FEUP',
        'Frango grelhado com esparguete',
        'Quinta feira',
        'Dieta'),
    Dish('Cafetaria - Restaurante FEUP',
        'Frango grelhado com esparguete',
        'Sexta feira',
        'Dieta'),

    //VEGETARIANO
    Dish('Cafetaria - Restaurante FEUP',
        'Muqueca de tofu',
        'Segunda feira',
        'Vegetariano'),
    Dish('Cafetaria - Restaurante FEUP',
        'Muqueca de tofu',
        'Terça feira',
        'Vegetariano'),
    Dish('Cafetaria - Restaurante FEUP',
        'Muqueca de tofu',
        'Quarta feira',
        'Vegetariano'),
    Dish('Cafetaria - Restaurante FEUP',
        'Muqueca de tofu',
        'Quinta feira',
        'Vegetariano'),
    Dish('Cafetaria - Restaurante FEUP',
        'Muqueca de tofu',
        'Sexta feira',
        'Vegetariano'),

    //INEGI
    //CARNE
    Dish('Restaurante do INEGI',
        'Frango assado com arroz de tomate',
        'Segunda feira',
        'Carne'),
    Dish('Restaurante do INEGI',
        'Lombo de porco assado com maçã',
        'Terça feira',
        'Carne'),
    Dish('Restaurante do INEGI',
        'Frango assado com arroz de tomate',
        'Quarta feira',
        'Carne'),
    Dish('Restaurante do INEGI',
        'Frango assado com arroz de tomate',
        'Quinta feira',
        'Carne'),
    Dish('Restaurante do INEGI',
        'Frango assado com arroz de tomate',
        'Sexta feira',
        'Carne'),

    //PEIXE
    Dish('Restaurante do INEGI',
        'Bacalhau fresco à zé do pipo',
        'Segunda feira',
        'Peixe'),
    Dish('Restaurante do INEGI',
        'Truta com bacon com batata cozida',
        'Terça feira',
        'Peixe'),
    Dish('Restaurante do INEGI',
        'Truta com bacon com batata cozida',
        'Quarta feira',
        'Peixe'),
    Dish('Restaurante do INEGI',
        'Truta com bacon com batata cozida',
        'Quinta feira',
        'Peixe'),
    Dish('Restaurante do INEGI',
        'Truta com bacon com batata cozida',
        'Sexta feira',
        'Peixe'),

    //DIETA
    Dish('Restaurante do INEGI',
        'Frango grelhado com esparguete',
        'Segunda feira',
        'Dieta'),
    Dish('Restaurante do INEGI',
        'Frango grelhado com esparguete',
        'Terça feira',
        'Dieta'),
    Dish('Restaurante do INEGI',
        'Frango grelhado com esparguete',
        'Quarta feira',
        'Dieta'),
    Dish('Restaurante do INEGI',
        'Frango grelhado com esparguete',
        'Quinta feira',
        'Dieta'),
    Dish('Restaurante do INEGI',
        'Frango grelhado com esparguete',
        'Sexta feira',
        'Dieta'),

    //VEGETARIANO
    Dish('Restaurante do INEGI',
        'Muqueca de tofu',
        'Segunda feira',
        'Vegetariano'),
    Dish('Restaurante do INEGI',
        'Muqueca de tofu',
        'Terça feira',
        'Vegetariano'),
    Dish('Restaurante do INEGI',
        'Muqueca de tofu',
        'Quarta feira',
        'Vegetariano'),
    Dish('Restaurante do INEGI',
        'Muqueca de tofu',
        'Quinta feira',
        'Vegetariano'),
    Dish('Restaurante do INEGI',
        'Muqueca de tofu',
        'Sexta feira',
        'Vegetariano'),

    //Cantina Almoço
    //CARNE
    Dish('Cantina - Almoço',
        'Frango assado com arroz de tomate',
        'Segunda feira',
        'Carne'),
    Dish('Cantina - Almoço',
        'Lombo de porco assado com maçã',
        'Terça feira',
        'Carne'),
    Dish('Cantina - Almoço',
        'Frango assado com arroz de tomate',
        'Quarta feira',
        'Carne'),
    Dish('Cantina - Almoço',
        'Frango assado com arroz de tomate',
        'Quinta feira',
        'Carne'),
    Dish('Cantina - Almoço',
        'Frango assado com arroz de tomate',
        'Sexta feira',
        'Carne'),

    //PEIXE
    Dish('Cantina - Almoço',
        'Bacalhau fresco à zé do pipo',
        'Segunda feira',
        'Peixe'),
    Dish('Cantina - Almoço',
        'Truta com bacon com batata cozida',
        'Terça feira',
        'Peixe'),
    Dish('Cantina - Almoço',
        'Truta com bacon com batata cozida',
        'Quarta feira',
        'Peixe'),
    Dish('Cantina - Almoço',
        'Truta com bacon com batata cozida',
        'Quinta feira',
        'Peixe'),
    Dish('Cantina - Almoço',
        'Truta com bacon com batata cozida',
        'Sexta feira',
        'Peixe'),

    //DIETA
    Dish('Cantina - Almoço',
        'Frango grelhado com esparguete',
        'Segunda feira',
        'Dieta'),
    Dish('Cantina - Almoço',
        'Frango grelhado com esparguete',
        'Terça feira',
        'Dieta'),
    Dish('Cantina - Almoço',
        'Frango grelhado com esparguete',
        'Quarta feira',
        'Dieta'),
    Dish('Cantina - Almoço',
        'Frango grelhado com esparguete',
        'Quinta feira',
        'Dieta'),
    Dish('Cantina - Almoço',
        'Frango grelhado com esparguete',
        'Sexta feira',
        'Dieta'),

    //VEGETARIANO
    Dish('Cantina - Almoço',
        'Muqueca de tofu',
        'Segunda feira',
        'Vegetariano'),
    Dish('Cantina - Almoço',
        'Muqueca de tofu',
        'Terça feira',
        'Vegetariano'),
    Dish('Cantina - Almoço',
        'Muqueca de tofu',
        'Quarta feira',
        'Vegetariano'),
    Dish('Cantina - Almoço',
        'Muqueca de tofu',
        'Quinta feira',
        'Vegetariano'),
    Dish('Cantina - Almoço',
        'Muqueca de tofu',
        'Sexta feira',
        'Vegetariano'),

    //Cantina Jantar
    //CARNE
    Dish('Cantina - Jantar',
        'Frango assado com arroz de tomate',
        'Segunda feira',
        'Carne'),
    Dish('Cantina - Jantar',
        'Lombo de porco assado com maçã',
        'Terça feira',
        'Carne'),
    Dish('Cantina - Jantar',
        'Frango assado com arroz de tomate',
        'Quarta feira',
        'Carne'),
    Dish('Cantina - Jantar',
        'Frango assado com arroz de tomate',
        'Quinta feira',
        'Carne'),
    Dish('Cantina - Jantar',
        'Frango assado com arroz de tomate',
        'Sexta feira',
        'Carne'),

    //PEIXE
    Dish('Cantina - Jantar',
        'Bacalhau fresco à zé do pipo',
        'Segunda feira',
        'Peixe'),
    Dish('Cantina - Jantar',
        'Truta com bacon com batata cozida',
        'Terça feira',
        'Peixe'),
    Dish('Cantina - Jantar',
        'Truta com bacon com batata cozida',
        'Quarta feira',
        'Peixe'),
    Dish('Cantina - Jantar',
        'Truta com bacon com batata cozida',
        'Quinta feira',
        'Peixe'),
    Dish('Cantina - Jantar',
        'Truta com bacon com batata cozida',
        'Sexta feira',
        'Peixe'),

    //DIETA
    Dish('Cantina - Jantar',
        'Frango grelhado com esparguete',
        'Segunda feira',
        'Dieta'),
    Dish('Cantina - Jantar',
        'Frango grelhado com esparguete',
        'Terça feira',
        'Dieta'),
    Dish('Cantina - Jantar',
        'Frango grelhado com esparguete',
        'Quarta feira',
        'Dieta'),
    Dish('Cantina - Jantar',
        'Frango grelhado com esparguete',
        'Quinta feira',
        'Dieta'),
    Dish('Cantina - Jantar',
        'Frango grelhado com esparguete',
        'Sexta feira',
        'Dieta'),

    //VEGETARIANO
    Dish('Cantina - Jantar',
        'Muqueca de tofu',
        'Segunda feira',
        'Vegetariano'),
    Dish('Cantina - Jantar',
        'Muqueca de tofu',
        'Terça feira',
        'Vegetariano'),
    Dish('Cantina - Jantar',
        'Muqueca de tofu',
        'Quarta feira',
        'Vegetariano'),
    Dish('Cantina - Jantar',
        'Muqueca de tofu',
        'Quinta feira',
        'Vegetariano'),
    Dish('Cantina - Jantar',
        'Muqueca de tofu',
        'Sexta feira',
        'Vegetariano'),

    //INESCTEC
    //CARNE
    Dish('Bar INESC TEC',
        'Frango assado com arroz de tomate',
        'Segunda feira',
        'Carne'),
    Dish('Bar INESC TEC',
        'Lombo de porco assado com maçã',
        'Terça feira',
        'Carne'),
    Dish('Bar INESC TEC',
        'Frango assado com arroz de tomate',
        'Quarta feira',
        'Carne'),
    Dish('Bar INESC TEC',
        'Frango assado com arroz de tomate',
        'Quinta feira',
        'Carne'),
    Dish('Bar INESC TEC',
        'Frango assado com arroz de tomate',
        'Sexta feira',
        'Carne'),

    //PEIXE
    Dish('Bar INESC TEC',
        'Bacalhau fresco à zé do pipo',
        'Segunda feira',
        'Peixe'),
    Dish('Bar INESC TEC',
        'Truta com bacon com batata cozida',
        'Terça feira',
        'Peixe'),
    Dish('Bar INESC TEC',
        'Truta com bacon com batata cozida',
        'Quarta feira',
        'Peixe'),
    Dish('Bar INESC TEC',
        'Truta com bacon com batata cozida',
        'Quinta feira',
        'Peixe'),
    Dish('Bar INESC TEC',
        'Truta com bacon com batata cozida',
        'Sexta feira',
        'Peixe'),

    //DIETA
    Dish('Bar INESC TEC',
        'Frango grelhado com esparguete',
        'Segunda feira',
        'Dieta'),
    Dish('Bar INESC TEC',
        'Frango grelhado com esparguete',
        'Terça feira',
        'Dieta'),
    Dish('Bar INESC TEC',
        'Frango grelhado com esparguete',
        'Quarta feira',
        'Dieta'),
    Dish('Bar INESC TEC',
        'Frango grelhado com esparguete',
        'Quinta feira',
        'Dieta'),
    Dish('Bar INESC TEC',
        'Frango grelhado com esparguete',
        'Sexta feira',
        'Dieta'),

    //VEGETARIANO
    Dish('Bar INESC TEC',
        'Muqueca de tofu',
        'Segunda feira',
        'Vegetariano'),
    Dish('Bar INESC TEC',
        'Muqueca de tofu',
        'Terça feira',
        'Vegetariano'),
    Dish('Bar INESC TEC',
        'Muqueca de tofu',
        'Quarta feira',
        'Vegetariano'),
    Dish('Bar INESC TEC',
        'Muqueca de tofu',
        'Quinta feira',
        'Vegetariano'),
    Dish('Bar INESC TEC',
        'Muqueca de tofu',
        'Sexta feira',
        'Vegetariano')
  ];
}

